dist: trusty

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7', 'g++-8']

before_install:
# TODO: I usually make builds with 5.14 - Duke
 - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
 - sudo apt-get update -qq
 - sudo apt-get install qt59base
 - source /opt/qt59/bin/qt59-env.sh
 - chmod +x res/libsodium/buildlibsodium.sh

script:
 - qmake -v
 - clang++ -v
 - g++-8 -v
  # Linguist test that translation source files can be compiled
  # correctly and will hopefully catch syntax errors earlier
  # We want the build to fail if we can't compile translations.
 - ./build.sh linguist
 - qmake silentdragon.pro CONFIG+=release -spec linux-clang
 - make CC=clang CXX=clang++ -j2
 - make distclean
 - qmake silentdragon.pro CONFIG+=release -spec linux-g++
 - res/libsodium/buildlibsodium.sh
 - make CC=gcc-8 CXX=g++-8 -j2
